# Generated by Django 5.2.8 on 2026-02-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('tecnologia', 'Tecnología'), ('hogar', 'Hogar'), ('moda', 'Moda'), ('deporte', 'Deporte'), ('vehiculos', 'Vehículos'), ('otros', 'Otros')], default='otros', max_length=20),
            preserve_default=False,
        ),
    ]
